spring:
  profiles:
    active: test
  devtools:
    restart:
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xu.viewpoint.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



