spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/viewpoint?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379

  servlet:
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB


rocketmq:
  name:
    server:
      address: 127.0.0.1:9876


fdfs:
  so-timeout: 6000	#修改之后的
  connect-timeout: 6000	# 修改之后的
  thumb-image:
    height: 150
    width: 150
  tracker-list: 192.168.59.100:2024
  http:
    storage-addr: http://192.168.59.100:8888/group1/









